Repository digdir/designsystemet, pull requests merged in 2023-10, with the labels that each got.

#857 feat(DosAndDonts): Add Do and Dont component
  assets/img/component-guidelines/alert/alert-ex1-do.png
  assets/img/component-guidelines/alert/alert-ex1-dont.png
  assets/img/component-placeholders/accordion.png
  assets/img/component-placeholders/alert.png
  assets/img/component-placeholders/button.png
  assets/img/component-placeholders/checkbox-group.png
  assets/img/component-placeholders/checkbox.png
  assets/img/component-placeholders/fieldset.png
  assets/img/component-placeholders/help-text.png
  assets/img/component-placeholders/list.png
  assets/img/component-placeholders/popover.png
  assets/img/component-placeholders/radio-button-group.png
  assets/img/component-placeholders/radio-button.png
  assets/img/component-placeholders/select.png
  assets/img/component-placeholders/spinner.png
  assets/img/component-placeholders/table.png
  assets/img/component-placeholders/tabs.png
  assets/img/component-placeholders/text-field.png
  assets/img/component-placeholders/textarea.png
  assets/img/component-placeholders/toggle-button.png
  docs-components/DoAndDont/DoAndDont.module.css
  docs-components/DoAndDont/DoAndDont.tsx
  docs-components/Stack/Stack.module.css
  docs-components/Stack/Stack.tsx
  docs-components/index.ts
  packages/react/src/components/Alert/Alert.mdx
Labels: component, 📔 storybook, 🖥️ storefront

#876 feat(Tabs): :sparkles: New `Tabs` Component
  packages/Overview.mdx
  packages/react/src/components/Tabs/Tab/Tab.module.css
  packages/react/src/components/Tabs/Tab/Tab.test.tsx
  packages/react/src/components/Tabs/Tab/Tab.tsx
  packages/react/src/components/Tabs/Tab/index.ts
  packages/react/src/components/Tabs/Tab/useTab.ts
  packages/react/src/components/Tabs/TabContent/TabContent.module.css
  packages/react/src/components/Tabs/TabContent/TabContent.test.tsx
  packages/react/src/components/Tabs/TabContent/TabContent.tsx
  packages/react/src/components/Tabs/TabContent/index.ts
  packages/react/src/components/Tabs/TabList/TabList.module.css
  packages/react/src/components/Tabs/TabList/TabList.test.tsx
  packages/react/src/components/Tabs/TabList/TabList.tsx
  packages/react/src/components/Tabs/TabList/index.ts
  packages/react/src/components/Tabs/Tabs.mdx
  packages/react/src/components/Tabs/Tabs.stories.tsx
  packages/react/src/components/Tabs/Tabs.test.tsx
  packages/react/src/components/Tabs/Tabs.tsx
  packages/react/src/components/Tabs/index.ts
Labels: 📔 storybook

#818 chore(storefront): Add CSS tokens to components
  storefront/components/Banner/Banner.module.css
  storefront/components/Card/Card.module.css
  storefront/components/Card/Card.tsx
  storefront/components/Card/index.ts
  storefront/components/CodeSnippet/CodeSnippet.module.css
  storefront/components/CodeSnippet/CodeSnippet.tsx
  storefront/components/Footer/Footer.module.css
  storefront/components/Grid/Grid.module.css
  storefront/components/Header/Header.module.css
  storefront/components/Header/Header.tsx
  storefront/components/ImageSection/ImageSection.module.css
  storefront/components/JumpToMain/JumpToMain.module.css
  storefront/components/MdxContent/MdxContent.module.css
  storefront/components/NavigationCard/NavigationCard.module.css
  storefront/components/ResponsiveIframe/ResponsiveIframe.module.css
  storefront/components/Section/Section.module.css
  storefront/components/SidebarMenu/SidebarMenu.module.css
  storefront/components/Tag/Tag.module.css
  storefront/components/Tokens/TokenFontSize/TokenFontSize.module.css
  storefront/components/Tokens/TokenList/TokenList.module.css
  storefront/components/Usage/ComponentUsage.module.css
  storefront/components/Usage/ComponentUsage.tsx
  storefront/components/Usage/index.ts
  storefront/components/index.ts
  storefront/globals.css
  storefront/layouts/MenuPageLayout/MenuPageLayout.module.css
  storefront/layouts/NavPageLayout/NavPageLayout.tsx
  storefront/tokens/tokens.css
Labels: 🖥️ storefront

#908 chore(storefront): Remove react query and update Next.js
  storefront/package.json
  storefront/pages/_app.tsx
  yarn.lock
Labels: 🖥️ storefront

#938 feat(Button): New `variants` and minor fixes
  packages/Overview.mdx
  packages/react/src/components/Button/Button.mdx
  packages/react/src/components/Button/Button.module.css
  packages/react/src/components/Button/Button.stories.tsx
  packages/react/src/components/Button/Button.test.tsx
  packages/react/src/components/Button/Button.tsx
  packages/react/src/components/Pagination/Pagination.tsx
Labels: 📔 storybook
