Repository digdir/designsystemet, pull requests merged in 2023-06, with the labels that each got.

#502 fix(InputWrapper): should only show invalid variant when field is invalid
  packages/react/src/components/_InputWrapper/InputWrapper.test.tsx
  packages/react/src/components/_InputWrapper/InputWrapper.tsx
Labels: 🐛 bug

#515 refactor(InputWrapper): use the ErrorMessage and Paragraph
  packages/react/src/components/_InputWrapper/InputWrapper.module.css
  packages/react/src/components/_InputWrapper/InputWrapper.tsx
Labels: react

#550 refactor(Tag): should use border radius tokens
  packages/react/src/components/Tag/Tag.module.css
  packages/react/stories/core.stories.mdx
Labels: 🐛 bug, component

#566 docs(Checkbox): story should be interactive
  packages/react/src/components/Checkbox/Checkbox.stories.tsx
Labels: 📔 storybook

#582 refactor: Export all in components/index.ts
  packages/react/src/components/index.ts
Labels: ⚙️ technical
