Repository digdir/designsystemet, pull requests merged in 2023-11, with the labels that each got.

#1087 docs: updated information about the designsystem
  apps/storefront/pages/grunnleggende/introduksjon/om-designsystemet.mdx
Labels: 🖥️ storefront

#904 docs: improved guidelines for checkbox
  assets/img/component-guidelines/checkbox/CheckboxGroupH.png
  assets/img/component-guidelines/checkbox/CheckboxGroupV.png
  packages/react/src/components/form/Checkbox/Checkbox.mdx
  packages/react/src/components/form/Checkbox/Checkbox.stories.tsx
  packages/react/src/components/form/Checkbox/Group/Group.stories.tsx
Labels: 📔 storybook

#1051 ci: Test fix for cleanup action for preview deployments
  .github/workflows/cleanup-preview-deployments.yml
Labels: ♿️ accessibility
