Repository digdir/designsystemet, pull requests merged in 2023-09, with the labels that each got.

#798 fix(Radio, Checkbox, Switch): :bug: Remove z-index on selection control icon
  packages/react/src/components/form/Checkbox/Checkbox.module.css
  packages/react/src/components/form/Radio/Radio.module.css
  packages/react/src/components/form/Switch/Switch.module.css
Labels: 📔 storybook

#815 fix(Accordion): hide content in Accordions from screen readers when Accordion is closed
  packages/react/src/utility-components/AnimateHeight/AnimateHeight.module.css
Labels: 🐛 bug, ♿️ accessibility

#665 chore: improve token preview in storefront
  .eslintrc.js
  packages/tokens/brand/altinn/tokens.cjs.js
  packages/tokens/brand/altinn/tokens.css
  packages/tokens/brand/altinn/tokens.esm.js
  packages/tokens/brand/brreg/tokens.cjs.js
  packages/tokens/brand/brreg/tokens.css
  packages/tokens/brand/brreg/tokens.esm.js
  packages/tokens/brand/digdir/tokens.cjs.js
  packages/tokens/brand/digdir/tokens.css
  packages/tokens/brand/digdir/tokens.esm.js
  packages/tokens/brand/tilsynet/tokens.cjs.js
  packages/tokens/brand/tilsynet/tokens.css
  packages/tokens/brand/tilsynet/tokens.esm.js
  packages/tokens/scripts/build.ts
  packages/tokens/scripts/formatters.ts
  storefront/components/ClipboardBtn/ClipboardBtn.module.css
  storefront/components/ClipboardBtn/ClipboardBtn.tsx
  storefront/components/MdxContent/MdxContent.module.css
  storefront/components/Section/index.ts
  storefront/components/TableOfContents/TableOfContents.module.css
  storefront/components/TableOfContents/TableOfContents.tsx
  storefront/components/TableOfContents/index.ts
  storefront/components/Tokens/TokenColor/TokenColor.module.css
  storefront/components/Tokens/TokenColor/TokenColor.tsx
  storefront/components/Tokens/TokenFontSize/TokenFontSize.module.css
  storefront/components/Tokens/TokenList.module.css
  storefront/components/Tokens/TokenList.tsx
  storefront/components/Tokens/TokenList/TokenList.module.css
  storefront/components/Tokens/TokenList/TokenList.tsx
  storefront/components/Tokens/TokenShadow/TokenShadow.module.css
  storefront/components/Tokens/TokenSize/TokenSize.module.css
  storefront/components/Tokens/TokenSize/TokenSize.tsx
  storefront/components/Tokens/index.ts
  storefront/components/index.ts
  storefront/globals.css
  storefront/layouts/MenuPageLayout/MenuPageLayout.module.css
  storefront/layouts/MenuPageLayout/MenuPageLayout.tsx
  storefront/package.json
  storefront/pages/_app.tsx
  storefront/pages/grunnleggende/designelementer/farger.mdx
  storefront/pages/grunnleggende/designelementer/sizing.mdx
  storefront/pages/grunnleggende/designelementer/skygger.mdx
  storefront/pages/grunnleggende/designelementer/spacing.mdx
  storefront/pages/grunnleggende/designelementer/typografi.mdx
  storefront/tokens/altinn.ts
  storefront/tokens/brreg.ts
  storefront/tokens/digdir.ts
  storefront/tokens/tilsynet.ts
  storefront/utils/StringHelpers.tsx
  yarn.lock
Labels: 🖥️ storefront

#839 feat(ErrorMessage): Add Large size token
  design-tokens/Base/Semantic.json
  packages/tokens/brand/altinn/tokens.cjs.js
  packages/tokens/brand/altinn/tokens.css
  packages/tokens/brand/altinn/tokens.d.ts
  packages/tokens/brand/altinn/tokens.esm.js
  packages/tokens/brand/brreg/tokens.cjs.js
  packages/tokens/brand/brreg/tokens.css
  packages/tokens/brand/brreg/tokens.d.ts
  packages/tokens/brand/brreg/tokens.esm.js
  packages/tokens/brand/digdir/tokens.cjs.js
  packages/tokens/brand/digdir/tokens.css
  packages/tokens/brand/digdir/tokens.d.ts
  packages/tokens/brand/digdir/tokens.esm.js
  packages/tokens/brand/tilsynet/tokens.cjs.js
  packages/tokens/brand/tilsynet/tokens.css
  packages/tokens/brand/tilsynet/tokens.d.ts
  packages/tokens/brand/tilsynet/tokens.esm.js
  storefront/tokens/altinn.ts
  storefront/tokens/brreg.ts
  storefront/tokens/digdir.ts
  storefront/tokens/tilsynet.ts
Labels: 📔 storybook

#816 feat(Textfield): :sparkles: New `Textfield` component
  packages/Overview.mdx
  packages/react/src/components/form/CharacterCounter.tsx
  packages/react/src/components/form/Textfield/TextField.test.tsx
  packages/react/src/components/form/Textfield/Textfield.mdx
  packages/react/src/components/form/Textfield/Textfield.module.css
  packages/react/src/components/form/Textfield/Textfield.stories.tsx
  packages/react/src/components/form/Textfield/Textfield.tsx
  packages/react/src/components/form/Textfield/index.ts
  packages/react/src/components/form/Textfield/useTextfield.ts
  packages/react/src/components/index.ts
Labels: 📔 storybook

#796 chore(storefront): add CSS tokens and clean code for layouts
  storefront/components/MdxContent/MdxContent.module.css
  storefront/globals.css
  storefront/layouts/FrontpageLayout/FrontpageLayout.module.css
  storefront/layouts/FrontpageLayout/FrontpageLayout.tsx
  storefront/layouts/MenuPageLayout/MenuPageLayout.module.css
  storefront/layouts/MenuPageLayout/MenuPageLayout.tsx
  storefront/layouts/NavMenuPageLayout/NavMenuPageLayout.module.css
  storefront/layouts/NavMenuPageLayout/NavMenuPageLayout.tsx
  storefront/layouts/NavPageLayout/NavPageLayout.module.css
  storefront/layouts/NavigationPageLayout/NavigationPageLayout.module.css
  storefront/layouts/NotFoundLayout/NotFoundLayout.module.css
  storefront/layouts/NotFoundLayout/NotFoundLayout.tsx
  storefront/layouts/PageLayout/PageLayout.module.css
  storefront/layouts/PageLayout/PageLayout.tsx
  storefront/layouts/index.tsx
  storefront/pages/grunnleggende/index.mdx
  storefront/pages/index.mdx
  storefront/pages/monstre/index.mdx
Labels: 🖥️ storefront

#813 feat(ToggleGroup): ✨ New `ToggleGroup` component
  packages/Overview.mdx
  packages/react/src/components/ToggleGroup/ToggleGroup.mdx
  packages/react/src/components/ToggleGroup/ToggleGroup.module.css
  packages/react/src/components/ToggleGroup/ToggleGroup.stories.tsx
  packages/react/src/components/ToggleGroup/ToggleGroup.test.tsx
  packages/react/src/components/ToggleGroup/ToggleGroup.tsx
  packages/react/src/components/ToggleGroup/ToggleGroupItem/ToggleGroupItem.module.css
  packages/react/src/components/ToggleGroup/ToggleGroupItem/ToggleGroupItem.tsx
  packages/react/src/components/ToggleGroup/ToggleGroupItem/useToggleGroupitem.ts
  packages/react/src/components/ToggleGroup/index.ts
  packages/react/src/utility-components/RovingTabIndex/RovingTabindexItem.tsx
  packages/react/src/utility-components/RovingTabIndex/RovingTabindexRoot.test.tsx
  packages/react/src/utility-components/RovingTabIndex/RovingTabindexRoot.tsx
  packages/react/src/utility-components/RovingTabIndex/index.ts
  packages/react/src/utility-components/RovingTabIndex/useRovingTabindex.ts
Labels: 📔 storybook

#824 feat: avoid misunderstanding of primary and secondary
  design-tokens/$themes.json
  design-tokens/Base/Semantic.json
  design-tokens/Brand/Altinn.json
  design-tokens/Brand/Brreg.json
  design-tokens/Brand/Digdir.json
  design-tokens/Brand/Tilsynet.json
Labels: 🖥️ storefront
